# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(default=datetime.datetime(2016, 6, 2, 17, 53, 29, 283586, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
