# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
